### ISSUE TITLE
fast-eslint trow errors when no configuration files are found

### ISSUE THREAD

**Issue by gael-boyenval** [Adezandee/fast-eslint#166]
An option allowing fast-eslint to not activate himself when no .eslintrc file is found in the project folder would be great. 

For exemple, downloading and exploring a package from the web in atom trow error at each opening of a javascript file. Pretty annoying… 

Even if this package is a great tool and serve is purpose more than nicely in a everyday workflow, this behavior make him a 'disable-right-away' kind of extension to me.

regards.

**Comment by jhabdas** [comment]
`Error: No ESLint configuration found.`

<img width="458" alt="screen shot 2016-08-14 at 6 42 14 am" src="https://cloud.githubusercontent.com/assets/440298/17648877/7458cf34-61ea-11e6-82a5-1e92249e24b9.png">

**Comment by Adezandee** [comment]
Hello @jhabdas, yes since eslint v3 a configuration file is needed. See https://github.com/Adezandee/fast-eslint/blob/master/README.md#L18
Otherwise @gael-boyenval I'am open to suggestion & PR to diverge from eslint standard behavior, is there a way to correctly handle possible configuration locations and dectect if its present or not ?

**Comment by SteveAquino** [comment]
@Adezandee I have to agree that this behavior makes this plugin extremely difficult to use.  At my organization we've recently introduced eslint into SOME of our projects, but not all of them.  This makes it almost impossible to work on those other projects without those annoying error.  In my opinion, this should be at least be configurable in the plugin's settings.  I'm not familiar with building plugins for atom, but I can't imagine this to be too difficult.

**Comment by jhabdas** [comment]
Personally I've moved onto StandardJS as it's more forgiving as a linter, and who really needs ALL that complexity. That said, it's Atom plug-in has the same bug. I'd expect any linting package to do some feature detection before throwing.
