### ISSUE TITLE
Unexpected top-level property "ecmaFeatures"

### ISSUE THREAD

**Issue by Germain67** [Adezandee/fast-eslint#255]
With the recent update I am getting the following error on our project.
`Error: [object Object]: ESLint configuration is invalid: - Unexpected top-level property "ecmaFeatures".`

Do you have any hint ? :)

**Comment by Adezandee** [comment]
Hello @Germain67, what is your eslint configuration ?
Seems like `ecmaFeatures` should be placed under `parserOptions` like so:
``` json
{
    "parserOptions": {
        "ecmaFeatures": {
            "globalReturn": false
        }
    }
}
```

**Comment by Germain67** [comment]
hello @Adezandee , thanks for your fast answer !

We actually an .eslintrc looking like this
```
{
    "ecmaFeatures": {},
    "parser": "espree",
   [... some more props]
}
```

Did the es-lint format supported by your extension change with this new release ?
It was working great on 3.x version !

PS : My other colleagues work on visual studio code and it works with this configuration.

**Comment by Adezandee** [comment]
Yeah, it's from the upgrade to ESLint v4. The issue has been raised here: https://github.com/eslint/eslint/issues/8726

**Comment by Adezandee** [comment]
If you wish to downgrade in the meantime, you can by running:
```sh
$ apm install fast-eslint@3.13.0
```

**Comment by Germain67** [comment]
Okay, I will downgrade to 3.13 in that case !
Do you think they will add legacy support to ESLint v4 or I need to add it in the parserOptions ?

Thanks for your time :)
