### ISSUE TITLE
Installing fast-eslint causes crash on opening js file

### ISSUE THREAD

**Issue by slimjim777** [Adezandee/fast-eslint#26]
Opening any Javascript file is now causing an issue. Everything was working until I upgraded to the current fast-eslint version.

My .eslintrc:

```
{
  "parser": "babel-eslint",

  "env": {
      "browser": true,
      "node": true,
      "es6": true
  },

  "rules": {
    // needed for eslint
    "strict": 0,

    // react stuff
    "react/jsx-boolean-value": 1,
    "react/jsx-no-undef": 2,
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-unknown-property": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/wrap-multilines": 1
  },

  "ecmaFeatures": {
        "jsx": true,
        "modules": true
  },

  "plugins": [
    "react"
  ]
}
```

**Comment by Adezandee** [comment]
Hi @slimjim777, I couldn't reproduce your error.
What is the eslint / atom error message ?

**Comment by Adezandee** [comment]
@slimjim777, ok I released a fix https://github.com/Adezandee/fast-eslint/releases/tag/v2.2.1 locking eslint to version 2.2.x. This should solve your issue

**Comment by slimjim777** [comment]
I did have older versions installed (eslint 1.10.3, eslint-plugin-react 3.15.0) and uninstalling them from the project and allowing the package to manage the dependencies fixed the issue.

Thanks.
