### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by pcr910303** [Adezandee/fast-eslint#265]
Currently the version of `eslint` specified in `package.json` is `4.19.1` while the latest version of `eslint` is `5.15.3`.

This is producing errors.
e.g) "array-element-newline": "consistent" option is excluded and making "fatal: Error" :-(

**Comment by Adezandee** [comment]
hello @pcr910303 
Thanks for the report, I released a new version.
Tell me if its ok

**Comment by pcr910303** [comment]
@Adezandee Thanks! Can confirm it is running well for all eslint projects :-)
I'm not sure if original behavior did not display any linter errors if `.eslintrc.js` is not present.
Currently it does...
