### ISSUE TITLE
"Import is reserved" Error

### ISSUE THREAD

**Issue by batjko** [Adezandee/fast-eslint#30]
Just installed the package and opened a Javascript ES6 file that uses imports. 
Alas:

![image](https://cloud.githubusercontent.com/assets/7287076/13847552/b086e8ee-ec45-11e5-95a7-03bd6bc01d1a.png)

Maybe I misunderstood, do I have to configure anything before this package actually uses the "bundled" airbnb config (which I understood already supports ES6)?

Cheers

**Comment by Adezandee** [comment]
Hi @batjko,
You have to setup the minimum viable `eslint` configuration. Either through:
* `eslintrc.json`
``` json
{
  "extends": "airbnb"
}
```
* inside `package.json` with:
``` json
"eslintConfig": {
    "extends": "airbnb"
},
```

fast-eslint comes with several bundled presets, you have to tell witch one to use :)

**Comment by batjko** [comment]
Ah. Then I was confused by the "zeroconf" claim in the readme file.
No worries, I added the package.json option and that works fine now. Thanks!
