### ISSUE TITLE
Upgrading to 2.3.0 produces errors with old config.

### ISSUE THREAD

**Issue by thaggie** [Adezandee/fast-eslint#31]
And I get a whole load of errors along the lines of:

`/Users/thaggie/.atom/packages/fast-eslint/node_modules/eslint/conf/eslint.json:` 
Configuration for rule "no-alert" is invalid: Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "off").

Referenced from: `/Users/thaggie/dev/data-play/.eslintrc.js`

I've edited the file by hand following the instructions.

**Comment by Adezandee** [comment]
Hi @thaggie, sorry for this. I've upgraded `eslint` to `v2.4.0` but there is no mention of such a change. Still, I didn't know that `off` was a valid setting for a rule, at least it's no documented. So I guess that this error message is legit ?

**Comment by thaggie** [comment]
That's OK - it didn't block me as I could just edit the file.

To be clear, my conf file uses numbers it was the file under `.atom/packages/fast-eslint/node_modules/eslint/conf` that had the strings.

I upgraded atom to 1.6.0 as well but it's a part of fast-eslint.

**Comment by Adezandee** [comment]
@thaggie ah, my bad I didn't fully understand your point before my first answer.
I tried the `eslint:recommended` preset on one of my projects, I couldn't see the error. So I guess that's an edge case problem when upgrading the package. You probably had `eslint v2.2.0` loaded inside your Atom editor and then upgraded to `eslint v2.4.0` when updating `fast-eslint`. Configuration and presets are dynamically read each time by the internal CLI engine, this often leads to some incompatibility or weird states.

Anyway, reloading Atom solves 99% of those kinds of issues I have seen.
