### ISSUE TITLE
Cant use with eslint-import-resolver-webpack

### ISSUE THREAD

**Issue by stalniy** [Adezandee/fast-eslint#66]
I use webpack for my project and have aliases for directories in my webpack config. So, when I add 
```js
  "settings": {
    "import/resolver": "webpack"
  }
```
to my `.eslintrc` Atom hightlights all imports and says "Resolve error: unable to load resolver webpack". However cli version of eslint works as expected

**Comment by Adezandee** [comment]
Hi @stalniy, thanks for your report.
I've submitted a fix, could you try it and let me know ?

**Comment by stalniy** [comment]
Thanks!
