### ISSUE TITLE
This package added 268ms to startup time. [improvement]

### ISSUE THREAD

**Issue by krzychukula** [Adezandee/fast-eslint#89]
Can you somehow improve startup time? Right now it's the slowest package I use :)

**Comment by Adezandee** [comment]
Hi @krzychukula, I've submitted some changes going in that direction, but I think that most of the time is spent with `require('eslint')`, and that's out of my scope here

**Comment by Adezandee** [comment]
@krzychukula, startup time is down to `164ms` on my side with `v2.11.0`. Can you let me know from yours ?

**Comment by krzychukula** [comment]
fast-eslint198ms
fast-eslint121ms
fast-eslint120ms
fast-eslint135ms

Still the slowest with the next one around 77ms but improvement is HUGE! Thanks a lot! :)
